var picnic = [
    'Charger',
    'Money',
    'Camera',
    'First aid kit',
    'Mat',
    'Towel',
    'Parasol',
    'Flashlight',
    'Maps',
    'Packages',
    'Map',
    'Mosquito spray',
    'Switchblade',
    'Barbecue',
    'Coal',
    'Finjan Coffee',
    'Pot with lid',
    'Salad bowls',
    'Plates',
    'Hampers',
    'Ice bag',
    'Salt & Pepper',
    'Spices for meat',
    'Skewers',
    'Books',
    'Musical Instruments',
    'Potatoes and foil',
    'Mosquito spray',
    'Folding chairs',
    'Folding table',
    'Music player + speakers',
    'Sauces',
    'Ketchup',
    'mustard',
    'mayonnaise',
    'Canned Food',
    'Cutting board',
    'Mineral',
    'Water',
    'Warm Clothing',
    'Gas Grill',
    'Brush Steel',
    'Snacks',
    'Nuts',
    'Pitta Bread',
    'Chocolate Spread',
    'Fruits Vegetables',
    'Drinks',
    'Lemon',
    'Onion',
    'Toilet paper',
    'Salads',
    'Hummus',
    'Matbucha',
    'Eggplant',
    'Cheese'];
var beach = [
    'Money',
    'Sun cream',
    'Towels',
    'Mats and lungis',
    'Water',
    'Paddle ball',
    'Backgammon',
    'Fribzi',
    'Swimsuit',
    'Hat',
    'Parasol',
    'Folding chairs',
    'Soft drinks',
    'Drinks',
    'Fruits and Vegetables',
    'Sandwiches',
    'Snacks',
    'Nuts',
    'Warm Clothing',
    'Packages'];
var nature = ['Tent trips',
    'Pegs and poles (to strengthen the marquee)',
    'Ropes',
    'Sleeping bag',
    'Backpacking mattress',
    'Inflatable Double / Single + pump',
    'Mosquito Books',
    'Flashlight',
    'Cilli',
    'Mat',
    'Switchblade',
    'Folding chair',
    'Folding table',
    'Hammock',
    'Generator',
    'Fishing equipment',
    'Grilling',
    'Charcoal lighter',
    'Matches or lighter',
    'Tools for barbecues',
    'Gas burner',
    'Pot with lid',
    'Reusable plastic dishes',
    'Tablecloth',
    'Detergent + Lock Bright',
    'Bowl',
    'Cutting board',
    'Knives',
    'Spices',
    'Foil',
    'Skewers',
    'Cover the meat with tools ready',
    'Poyke pot',
    'Thermos drink hot / cold',
    'Paper towels or napkins',
    'Bottle opener',
    'Coffee slips',
    'Hampers',
    'Ice cooler',
    'Water',
    'Snacks',
    'Nuts',
    'Toilet paper and wipes',
    'Garbage bags',
    'Fruits and Vegetables',
    'Pitta',
    'Bread',
    'Drinks',
    'Cutting board',
    'Salads',
    'Change of clothes',
    'Warm Clothing',
    'Sunglasses',
    'Camera + recharge batteries',
    'Flashlight + Battery',
    'Charger',
    'Book Reading',
    'Notebook and pen',
    'Binoculars',
    'Map',
    'Board games',
    'Musical Instruments',
    'Music player + speakers',
    'Music player',
    'Toiletries',
    'First aid'];
var bbq = [
    'Tent trips',
    'Pegs and poles',
    'Ropes',
    'Sleeping bag',
    'Backpacking mattress',
    'Inflatable mattress',
    'Mosquito Books',
    'Flashlight',
    'Chili',
    'Mat',
    'Switchblade',
    'Folding chair',
    'Folding table',
    'Hammock',
    'Generator',
    'Fishing equipment',
    'Grilling',
    'Charcoal lighter',
    'Matches or lighter',
    'Tools for barbecues',
    'Gas burner',
    'Pot with lid',
    'Reusable plastic dishes',
    'Tablecloth',
    'Detergent + Lock Bright',
    'Bowl',
    'Cutting board',
    'Knives',
    'Spices',
    'Foil',
    'Skewers',
    'Poyke pot',
    'Thermos drink hot / cold',
    'Paper towels or napkins',
    'Bottle opener',
    'Coffee slips',
    'Hampers',
    'Ice cooler',
    'Water',
    'Snacks',
    'Nuts',
    'Toilet paper and wipes',
    'Garbage bags',
    'Pitta',
    'Bread',
    'Fruits and Vegetables',
    'Drinks',
    'Cutting board',
    'Salads',
    'Change of clothes',
    'Warm Clothing',
    'Sunglasses',
    'Camera + recharge batteries',
    'Flashlight + Battery',
    'Charger',
    'Book Reading',
    'Notebook and pen',
    'Binoculars',
    'Map',
    'Musical Instruments',
    'Music player',
    'Toiletries',
    'First aid'
];

var data = require('../libs/data');
var common = require('../libs/common');
var configDB = require('../config/database.js');
var mongoose = require('mongoose');
var User = require('../libs/models/user');
var Event = require('../libs/models/event');
var Product = require('../libs/models/product');

mongoose.connect(configDB.url);

var users = [
    {phone: '0505500011', name: 'Jossef', password: '1234'},
    {phone: '0505500011', name: 'Moshe', password: '1234'},
    {phone: '0505500012', name: 'Aharon', password: '1234'},
    {phone: '0505500013', name: 'David', password: '1234'},
    {phone: '0505500014', name: 'Lior', password: '1234'},
    {phone: '0505500015', name: 'Reut', password: '1234'},
    {phone: '0505500016', name: 'Adi', password: '1234'},
    {phone: '0505500017', name: 'Liat', password: '1234'}
];

User.remove().exec();

var seasons = ['summer', 'spring', 'winter', 'fall'];
var types = ['party', 'BBQ', 'beach'];
var count = 0;
var creatorUser = [0];

var userEntities = [];
users.forEach(function(user){
    var userEntity = new User();
    userEntity.phone = common.parsePhoneNumber(user.phone);
    userEntity.password = userEntity.generateHash(user.password);
    userEntity.nickname = user.name;
    userEntity.registered = true;
    userEntity.save();

    userEntities.push(userEntity);
});



